version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=ajfkls#dwe55954sdMMdf12#306!843
      - MYSQL_DATABASE=ShopTemplateDB
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=gg232412abb22#306!843
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: